name: Release
run-name: Release ${{ github.ref_name }} ${{ github.event.inputs.version }} Debian/Bullseye (crossbuild/arm64)

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        options:
        - 2.x
        - 3.x
  push:
    tags:
      - 2.**
      - 3.**

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build packages
      run: |
        if [[ "${{ github.event.inputs.version }}" =~ ^3. ]] || [[ "${GITHUB_REF_NAME}" =~ ^3. ]]; then
          pbsversion="pbs3"
        fi
        if [ "${RUNNER_DEBUG}" = "1" ]; then
          docker buildx build -o packages --build-arg buildoptions="cross github debug ${pbsversion}" --build-arg baseimage=debian:bullseye-slim --platform linux/amd64 -f .github/Dockerfile.crosscompile-arm64 .
        else
          docker buildx build -o packages --build-arg buildoptions="cross github ${pbsversion}" --build-arg baseimage=debian:bullseye-slim --platform linux/amd64 -f .github/Dockerfile.crosscompile-arm64 .
        fi
        echo "DEB_VERSION=$(dpkg --info packages/proxmox-backup-server_*.deb | sed -n '/Version/ s/[^:]\+: //p')" >> $GITHUB_ENV
        echo "DEB_VERSION_UPSTREAM=$(dpkg --info packages/proxmox-backup-server_*.deb | sed -n '/Version/ s/[^:]\+: \([0-9.]\+\)-[0-9]/\1/p')" >> $GITHUB_ENV
    - name: Test packages
      run: |
          docker buildx build --platform linux/arm64 -f .github/Dockerfile.installtest .
    - name: Release packages
      uses: ncipollo/release-action@v1
      with:
        artifacts: "packages/*.deb"
        bodyFile: "PREBUILD.md"
        tag:  ${{ env.DEB_VERSION }}
        name: Version ${{ env.DEB_VERSION }} (Debian/Bullseye)
        draft: true
